---
title: "Bem-vindo ao Mar de Nós"
page-layout: full
toc: false
execute:
  freeze: false
format:
  html:
    body-classes: home-page
---

<!--
  ____  _____ ____         _    ____  ____  _____ ____      _     
 |  _ \| ____|  _ \       / \  / ___||  _ \| ____|  _ \    / \    
 | |_) |  _| | |_) |     / _ \ \___ \| |_) |  _| | |_) |  / _ \   
 |  __/| |___|  _ <     / ___ \ ___) |  __/| |___|  _ <  / ___ \  
 |_|   |_____|_| \_\   /_/   \_\____/|_|   |_____|_| \_\/_/   \_\ 
     _    ____        _    ____ _____ ____      _    
    / \  |  _ \      / \  / ___|_   _|  _ \    / \   
   / _ \ | | | |    / _ \ \___ \ | | | |_) |  / _ \  
  / ___ \| |_| |   / ___ \ ___) || | |  _ <  / ___ \ 
 /_/   \_\____/   /_/   \_\____/ |_| |_| \_\/_/   \_\
-->

::: {.parallax}
<div class="title-box">
Bem-vindo ao Mar de Nós
</div>
:::

Este projeto é fruto de uma parceria entre a UFMG ([DESA](https://www.desa.ufmg.br/), [DERH](https://www.eng.ufmg.br/portal/dehr/), [DEST](https://www.est.ufmg.br/)), e atores engajados no Movimento Pró-Furnas 762, em especial: [ALAGO](https://www.instagram.com/alago.furnas/),  [Unelagos](https://www.instagram.com/unelagos/), e [FECITUR](https://www.fecitur.com.br/). 
A parceria foi iniciada em 2021 e se aprofundou em 2025, mediante financiamento ao Projeto de Pesquisa *“Saneamento básico em municípios da área de influência da represa de Furnas – MG: situação existente e relação com a participação e o controle social”*, por meio de emendas parlamentares.
<!--Depois citar Deputados [Odair Cunha](https://www.camara.leg.br/deputados/74159) e [Professor Cleiton](https://www.almg.gov.br/deputados/professor-cleiton/26119).-->

Nosso foco é na caracterização dos usos múltiplos da água e mecanismos de participação social como instrumentos para o engajamento voltado à construção de uma agenda comum entre os municípios que compõem a bacia e às ações coletivas de longo prazo e amplo alcance.


## O que você encontra aqui

::::::::::: grid

:::: {.g-col-12 .g-col-md-3}
::: {.card .h-100 .text-center .p-3}
<i class="bi bi-info-circle-fill fs-1 text-success"></i>
<a href="/sobre/index.qmd" class="text-decoration-none">Sobre o projeto</a><br>
Conheça a motivação, objetivos, metodologia e equipe por trás deste trabalho.
:::
::::

:::: {.g-col-12 .g-col-md-3}
::: {.card .h-100 .text-center .p-3}
<i class="bi bi-journal-text fs-1 text-warning"></i>
<a href="/blog/index.qmd" class="text-decoration-none"> Blog </a><br>
Artigos, tutoriais e insights sobre análise de dados e o projeto.
:::
::::

:::: {.g-col-12 .g-col-md-3}
::: {.card .h-100 .text-center .p-3}
<i class="bi bi-bar-chart-fill fs-1 text-danger"></i>
<a href="/app.qmd" class="text-decoration-none"> Dashboards </a><br>
Painéis interativos com análises e indicadores em tempo real.
:::
::::

:::: {.g-col-12 .g-col-md-3}
::: {.card .h-100 .text-center .p-3}
<i class="bi bi-box-seam-fill fs-1 text-primary"></i>
<a href="dados.qmd" class="text-decoration-none">Repositório de dados</a><br>
Uma curadoria de dados tratados sobre saneamento básico em Minas e no Brasil. 
:::
::::

:::::::::::


<!--style="width:110%; max-width:500px; min-height:500px; aspect-ratio: 5 / 7; border:none;"-->
## Destaques
::::: grid
::: {.g-col-12 .g-col-md-6}
<!--
<div style="text-align:center; margin-bottom:10px;">
  <p><strong>Acompanhe nosso projeto no Instagram!</strong></p>
</div>
-->
<div style="display:flex; justify-content:center;">
  <iframe 
    src="https://www.instagram.com/p/DP2HlqCgeRj/embed"
    style="width:100%; max-width:500px; min-height:500px; aspect-ratio: 5 / 7; border:none;"
    scrolling="no">
  </iframe>
</div>

:::


::: {.g-col-12 .g-col-md-6}

#### Último post do blog

```{r}
#| include: false
#```{r, cache=TRUE, cache.extra=file.info("stuff/df_ultimo_post.rds")$mtime}
df_ultimo_post = readRDS("stuff/df_ultimo_post.rds")
```


> [**`r df_ultimo_post$title`**](/blog/index.qmd)  
> *`r df_ultimo_post$author`, `r df_ultimo_post$date`*  
> `r df_ultimo_post$subtitle`.

<!--
#### Dashboard em destaque

> [**Painel SNIS**](https://dh3kih-carlos-de0moura.shinyapps.io/snis/)  
> *Análise fatorial com dados do SNIS*  
> Veja a construção e análise de indicadores sobre o saneamento em Minas Gerais.
-->

#### Documentos

> [**Autoindex**](autoindex/)  
> *Navegação automatizada de conteúdos*  
> Acesse uma lista organizada de documentos sobre o projeto.

#### Informações para desenvolvedores

> [**4devs**](/4devs/index.qmd)  
> *Recursos técnicos do projeto*  
> Acesse informações úteis sobre a programação e os códigos utilizados no projeto.
:::
:::::
