# Shiny Server Configuration
run_as moura; # run applications as the user specified

server {
  listen 3838; # Define a server that listens on specified port
  location / {
    site_dir /home/moura/Documents/website/dashboards; # Host the directory of Shiny Apps stored in this directory
    log_dir /home/moura/Documents/website/conf/shiny-logs; # Log all Shiny output to files in this directory
    directory_index on;
  }
}
