# Instruct Shiny Server to run applications as the user "shiny"
run_as shiny;

server {
  listen 10; # Define a server that listens on port 10
  location / {
    site_dir /home/moura/Documents/website/dashboards; # Host the directory of Shiny Apps stored in this directory
    log_dir /home/moura/Documents/website/conf/shiny-logs; # Log all Shiny output to files in this directory
    directory_index on;
  }
}
